language: node_js
node_js:
- '6'
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_2d5d49a6c100_key -iv $encrypted_2d5d49a6c100_iv
  -in rsa.enc -out $HOME/.ssh/rsa -d
env:
  global:
    secure: Ud7hBf/AQ13a9YYjO3/jNZx52euDXOdp3GgZJlbMGjbjvs1o4j+3AxPuTLmsFWKFmNaW6Of95XG92fa8+c26hxWzHEhURtmadTEJDpHHOBsTVZ8lSFuJi+st3Cb1Gc3M+peas+ack4EDsL0fAd3HjqLchvuj6/5cDsvHNh0v6OddFZjSg4v1XTdQVszjlOihLBwtGo3roUlO3EY47jE4HaulJISHFM9VCaXtG3GAItSqDUu+52dfxC7GeP5FB1OYQcxyuyi1bWGp8iwJUAGXZS3ovLEj3BirAkp9fHoA94iwBU42eJyNmpP54aLh/XwEsMo6Hmqqyu+vu469fvUJQYNMOHYOTQNHLdes6cz1+3oV24hmCwqpp+vxFGY/vXpqqXpjlYhvzLfhel5PWnwypekApWm40ua4o/JE1fxnsJCe5rTj3S3jPZONnbQsqoVkwp0Dde1bY/0VkoJuJN6/UTd5q4PjZLBBGp2X8JeInLREwNEo4p2deZjly/up3AgTI0ppsINM1+GC+TXEcE/8Rn4n+IvrChSawnN/CEvnsGHkcdq3sCeSWt+zDGJQa14c3QaU6prtu9ANBe2exkCA5y8pDlJv6dDtxbVUPEhYUh6dXgREDejVutqO3GhLZrkbEGrVCxavImUZXMt8wwIcpYb1fnTeKMKGTuykfRC9s+4=
