language: node_js
node_js:
- '6'
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_2d5d49a6c100_key -iv $encrypted_2d5d49a6c100_iv
  -in github_deploy_key.enc -out $HOME/.ssh/github_deploy_key -d
env:
  global:
    secure: E0ad6+FoH5um8hH3Z8rgqKbXHc05C+QdkxNFr6CipQTOUOFKxKC52+/MoFy89X1wxKzglT/oPl+Iy8lQHI5RNmQ5iifH4ZPghVMnyNVfB2MN+62e/uJ02BTz0k4Xl2FD2x9eWolxaBUoHbQNrenEaK21kX/v56WDMv7E95PkQ1X4ieGOZE97Uz2NumndWXnfTM9BKn06LKY+NDyw+n99M0rjYmqpyU/bqqigo/iwgi+ATPXVrkLEhKygv56fHABE7Fo3OZHRaKlxIAJ/SPOdukyR+wyZpbDGS874IPNgwEb+0exyhRFEanbffOPFtE1XchAzbv9E0R9/bTNdvh8GM47eSPcnaLHI/k0m/IewuesycrMLWJStHwOXqenQM4JRIMEXHnpRW72avlwSquB8IXvZbn8POTlHtx80oT6vfpDuigXwuz7xQlziXZE2gCDYqzvRrREU8qyfaLBxTvoGyBKrD+wWPGL2H8iN3dcjIo4LH+F/CRI8T9mwiu5luY8cx05Gf/fA1NJmAAXmO7UQT8L9Nqta5QkZD+/jvhfoJ1y4KCFKwzcdI35Ho0BfjH/Xn1R2fqwj+WWuQpgW5zSXhKNZgZgoaUmGmjHhN4+yTwgZqk1dPSKr1cTsyGf+JAJEzZp+lu3V7O6Mqc3GQQebF+Va66+9iN5W47vC3tiVMoo=
