language: node_js
node_js:
- '6'
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_2d5d49a6c100_key -iv $encrypted_2d5d49a6c100_iv
  -in github_deploy_key.enc -out github_deploy_key -d
env:
  global:
    secure: Q2fnQK3R3gsUnQxHzcqmDZohbuAvs/TuYGWX2fNYTQdy7jj4HxrYUOXDLLVrzqLUFiAaDlnoJg556oEt9dyiwI5ZuhN5WiJf1x3ZW8AFOLx1QSdOur1zHcsOt/fuJF1brZ5vU4I1yWwL4JCItp/9BgsH6xEp4pJS2R8ND4tUowWb4HWgFq4y165OVRyoNQlwp+4sGFFyrUbbuGQzp39oZsmthHT58ZSW6FnmQ9PqhZlgOSYe4L7cikXY3nofc0FzTvRBFVWD2XcWJOcRnG6kXSeLNwem6ByXblIpVIcpAu2vgtOr9sHQ4lpRyYEvX6y9m6I0u9VY0ggY2RaLaOXCZkTyUxb4nwv0mKLywekokxnpFSxy1yWrNuOq1T3t3i0IrQLjmdB0fhbcsfLJtRRH0K68k7wgefya54j7duKsUATYXw6qhVhJbsTktjGm/bzx4zrtDyxsy4bSQy+ERxONXdDRILYj6PUiEn0H91IIfoGMji1+CBa36PNzg/hWsv7vsYl+yGpQTlK/eUprg/clArWL5Tj3nFq0YX26C4x0jAZlyOCmyAbTf6mKH0c5KTf2hvc2STlOTVjOwDcNL3bIJVgCJj9ge2Hly/H3Ks34Q06+9HYbX0OEhMIHcOavUUtUjdsWWFKGEX8rgmoJEYUcf3mkU85FOgJQgpGQNw/0e6I=
