language: node_js
node_js:
- '6'
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy-travis
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_2d5d49a6c100_key -iv $encrypted_2d5d49a6c100_iv
  -in id_rsa.enc -out id_rsa -d
env:
  global:
    - DEPLOY_BRANCH="master"
    - SOURCE_DIR="dist"
    - TARGET_BRANCH="gh-pages"
    - SSH_KEY="id_rsa"
    - GIT_NAME="travis"
    - GIT_EMAIL="deploy@travis-ci.org"
