backend:
  name: github
  repo: nlarche/acadians # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "public/assets" 
public_folder: "/assets"

collections: # A list of collections the CMS should be able to edit
  - name: "home" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Home" # Used in the UI, e.g., "New Post"
    folder: "content/home" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Background", name: "Background", widget: "image"}
      - {label: "Video", name: "video", widget: "string"}      
      - {label: "Decription", name: "decription", widget: "string"}            
      - {label: "Publish Date", name: "date", widget: "datetime"}
  - name: "tour" 
    label: "Tour" 
    folder: "content/tour" 
    create: true 
    fields: 
      - {label: "Place", name: "place", widget: "string"}
      - {label: "Ville", name: "ville", widget: "image"}
      - {label: "Date", name: "date", widget: "datetime"}
  - name: "playlist" 
    label: "playLlist" 
    folder: "content/playlist" 
    create: true 
    fields: 
      - {label: "Titre", name: "titre", widget: "string"}     
      - {label: "url", name: "url", widget: "string"}        
      - {label: "Date", name: "date", widget: "datetime"}